### ISSUE TITLE
grade.py in proj-4 cs 450

### ISSUE THREAD

**Issue by vsag96** [ammarsubei/uic#1]
Hi Man, I am doing the cs450 course this semester and we are using same projects for our course as well. We were not provided test cases and not even the delay, loss and the max time our implementation must finish in to receive 12 points. I finished the HW and I used the grade.py provided here.

Here are my questions which I wanted to ask you.

1) Is the grade.py file provided by Professor teaching that semester? Because my implementation comfortably finished within the full_credit timeout. I think it was way too lenient with timeouts a program should finish in, so I was wondering if this was an official grading script.

2) Also for Proj_5, the buffer sizes are not provided to us, so does this mean we have to increase the buffer size until a packet loss occurs, like TCP?

**Comment by ammarsubei** [comment]
Yeah all `grade.py` scripts were provided by the course instructor(s). I remember the course being pretty lenient in general, so yeah I wouldn't be surprised.
As for the buffer size, I honestly don't recall the exact implementation but that should be a question for your instructor.

**Comment by vsag96** [comment]
Thanks for the update! I will be closing the issue.
